spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/company
    username: company
    password: company
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 3s
        failureRateThreshold: 50
        slowCallDurationThreshold: 3s
        recordExceptions:
          - feign.FeignException
          - feign.RetryableException
          - java.io.IOException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
    instances:
      license:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s

logging:
  level:
    io.github.resilience4j.timelimiter: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG