resilience4j:
  retry:
    instances:
      license:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - feign.FeignException
          - java.net.SocketTimeoutException
        ignoreExceptions:
          - feign.FeignException.BadRequest

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 2000
            loggerLevel: FULL

logging:
  level:
    io.github.resilience4j.retry: DEBUG
    com.msa.company.client: DEBUG