spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/company
    username: company
    password: company
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/msa-realm