spring:
  cloud:
    gateway:
      routes:
        - id: license
          uri: lb://license
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<segment>.*), /${segment}
        - id: company
          uri: lb://company
          predicates:
            - Path=/company/**

management:
  endpoint:
    gateway:
      enabled: true