spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: license
          uri: lb://license
          predicates:
            - Path=/license/**
        - id: company
          uri: lb://company
          predicates:
            - Path=/company/**
  reactor:
    context-propagation: auto

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/msa-realm

lgging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.cloud.gateway: debug
    reactor.netty: debug

management:
  endpoint:
    gateway:
      enabled: true