services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_vol:/opt/keycloak/data
    ports:
      - 8073:8080
    command:
      - start-dev
    networks:
      - msa_net
    restart: unless-stopped

  oracle:
    image: oracle
    container_name: oracle
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=oracle
      - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
    volumes:
      - oracle_vol:/opt/oracle/oradata
    networks:
      - msa_net
    deploy:
      resources:
        limits:
          memory: 2g
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s license/license@//localhost:1521/license"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: BROKER, CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /opt/kafka/data
    volumes:
      - kafka_vol:/opt/kafka/data
    networks:
      - msa_net
    restart: unless-stopped

  redis:
    image: redis:8.4-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_vol:/opt/redis/data
    networks:
      - msa_net
    restart: unless-stopped

  config:
    build:
      context: .
      args:
        SERVICE_NAME: config
    image: config
    container_name: config
    ports:
      - 8070:8070
    networks:
      - msa_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  eureka:
    build:
      context: .
      args:
        SERVICE_NAME: eureka
    image: eureka
    container_name: eureka
    ports:
      - 8071:8071
    networks:
      - msa_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  gateway:
    build:
      context: .
      args:
        SERVICE_NAME: gateway
    image: gateway
    container_name: gateway
    ports:
      - 8072:8072
    depends_on:
      config: {condition: service_healthy}
      eureka: {condition: service_healthy}
      keycloak: {condition: service_started}
      redis: {condition: service_started}
    networks:
      - msa_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8072/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  license:
    build:
      context: .
      args:
        SERVICE_NAME: license
    image: license
    container_name: license
    ports:
      - 8080:8080
    networks:
      - msa_net
    depends_on:
      oracle: {condition: service_healthy}
      config: {condition: service_healthy}
      eureka: {condition: service_healthy}
      keycloak: {condition: service_started}
      kafka: {condition: service_started}
      redis: {condition: service_started}
    restart: unless-stopped

  company:
    build:
      context: .
      args:
        SERVICE_NAME: company
    image: company
    environment:
      - SPRING_PROFILES_ACTIVE=rate
    container_name: company
    ports:
      - 8081:8081
    networks:
      - msa_net
    depends_on:
      oracle: { condition: service_healthy }
      config: { condition: service_healthy }
      eureka: { condition: service_healthy }
      keycloak: {condition: service_started}
      kafka: { condition: service_started }
      redis: { condition: service_started }
    restart: unless-stopped

volumes:
  oracle_vol:
    external: true
  keycloak_vol:
    external: true
  kafka_vol:
    external: true
  redis_vol:
    external: true

networks:
  msa_net:
    external: true